config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<%= render "form", flat: @flat %>
<%= link_to 'Back to home', flats_path, class: "btn btn-primary"%>

app/views/flats/index.html.erb
<h1>Our Flats</h1>
<br>
  <div class="cards">
        <% @flats.each do |flat| %>
          <div class="card-trip">
            <img src="https://images.unsplash.com/photo-1644292954519-dd04b8fc08a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" />
            <div class="card-trip-infos">
              <div>
                <h3><%= link_to flat.name, flat_path(flat) %></h3>
                <p><%= flat.address%></p>
                <p><%= '🧍' * flat.number_of_guests%></p>
              </div>
              <div>
                <h2 class="card-trip-pricing"><%= flat.price_per_night%>€</h2>
                <img src="https://images.unsplash.com/photo-1643198964380-a3d9a8b47f68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80" class="card-trip-user avatar-bordered" />
              </div>
            </div>
          </div>
          <% end %>
    </div>
<br>
<%= link_to 'Create New Flat', new_flat_path, class: "btn btn-primary"%>

app/views/flats/new.html.erb
<%= render "form", flat: @flat %>
<%= link_to 'Back to home', flats_path, class: "btn btn-primary"%>

app/views/flats/show.html.erb
<div class="card-trip">
  <img src="https://images.unsplash.com/photo-1644292954519-dd04b8fc08a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" />
  <div class="card-trip-infos">
    <div>
      <h1><%= @flat.name%></h1>
      <br>
      <h2>Address: </h2>
      <p><%= @flat.address%></p>
      <h2>Description: </h2>
      <p><%= @flat.description%></p>
      <h2>Number of guests: </h2>
      <p><%= '🧍' * @flat.number_of_guests%></p>
    </div>
    <h2 class="card-trip-pricing"><%= @flat.price_per_night%>€</h2>
    <img src="https://images.unsplash.com/photo-1643198964380-a3d9a8b47f68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80" class="card-trip-user avatar-bordered" />
  </div>
</div>
<div class="options">
  <div>
    <%= link_to 'Edit Flat', edit_flat_path(@flat), class:"btn btn-warning"%>
    <%= link_to flat_path(@flat), method: :delete,
                        data: { confirm: "Are you sure?" } do %>
                <div class="btn btn-danger">Delete Flat</div>
              <% end %>
    <div>
      <a class="btn btn-success" href="/flats">Back to flats</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1637710527019-b43708c651df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2076&q=80);">
      <div class="container">
        <h1>GroundBnB</h1>
        <p>Stay at a mountain themed home!</p>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>